version: '3.8'

services:
  ts-sol-playground:
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - VITE_API_URI=http://example-server:7300
      - NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}
    build:
      context: .
      target: ts-sol-playground-runner
    ports:
      - 3000:80
    healthcheck:
      # curl is not installed on this container so we use wget
      test: wget localhost:80 -q -O - > /dev/null 2>&1

  example-server:
    environment:
      - HOST=0.0.0.0
      - PORT=7300
      - NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}
    build:
      context: .
      target: example-server-runner
    ports:
      - 7300:7300
    healthcheck:
      # curl is not installed on this container so we use wget
      test: wget localhost:7300/api/healthz -q -O - > /dev/null 2>&1

  anvil:
    image: ghcr.io/foundry-rs/foundry
    platform: linux/amd64
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    command: anvil
    ports:
      - 8545:8545
    healthcheck:
      test: cast block-number --rpc-url http://0.0.0.0:8545

  contracts-deployer:
    platform: linux/amd64
    environment:
      - DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY}
    build:
      context: .
      target: contracts-deployer
    restart: "no"
    depends_on:
      anvil:
        condition: service_healthy

  forgecli:
    build:
      context: .
      target: forgecli

  e2e:
    environment:
      - BASE_URL=http://ts-sol-playground:3000
      - NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}
    build:
      target: e2e
      context: .
    depends_on:
      contracts-deployer:
        condition: service_completed_successfully
      ts-sol-playground:
        condition: service_healthy
      example-server:
        condition: service_healthy

  tests:
    build:
      target: monorepo
      context: .
    environment:
      - NX_CLOUD_ACCESS_TOKEN=${NX_CLOUD_ACCESS_TOKEN}