version: '3'

services:
  # React App
  example-ui:
    extends:
      file: docker-compose.base.yml
      service: base-app
    command: pnpm nx serve @roninjin10/example-ui
    ports:
      - 3000:3001

  # Fastify server
  example-server:
    extends:
      file: docker-compose.base.yml
      service: base-app
    command: pnpm nx serve @roninjin10/example-server
    ports:
      - 7300:7301

  anvil:
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    extends:
      file: docker-compose.base.yml
      service: base-app
    command: anvil
    ports:
      - 8545:8545
    healthcheck:
      test: cast block-number --rpc-url http://0.0.0.0:8545
      interval: 10s
      timeout: 5s
      retries: 5

  contracts:
    extends:
      file: docker-compose.base.yml
      service: base-app
    restart: "no"
    command: forge script packages/contracts/script/AppEntrypoint.s.sol:Deploy --rpc-url http://anvil:8545 --broadcast -vvvv
    depends_on:
      anvil:
        condition: service_healthy