version: '3.8'

services:
  example-ui:
    environment:
      - HOST=0.0.0.0
    extends:
      file: docker-compose.base.yml
      service: monorepo
    command: pnpm -F @roninjin10/example-ui serve
    ports:
      - 3000:3000
    healthcheck:
      test: curl http://0.0.0.0:7300

  example-server:
    environment:
      - HOST=0.0.0.0
    extends:
      file: docker-compose.base.yml
      service: monorepo
    command: pnpm -F @roninjin10/example-server serve
    ports:
      - 7300:7300
    healthcheck:
      test: curl http://0.0.0.0:3000/api/healthz

  anvil:
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    extends:
      file: docker-compose.base.yml
      service: monorepo
    command: anvil
    ports:
      - 8545:8545
    healthcheck:
      test: cast block-number --rpc-url http://0.0.0.0:8545

  contracts:
    extends:
      file: docker-compose.base.yml
      service: monorepo
    restart: "no"
    command: forge script packages/contracts/script/AppEntrypoint.s.sol:Deploy --rpc-url http://anvil:8545 --broadcast -vvvv
    depends_on:
      anvil:
        condition: service_healthy

  e2e:
    environment:
      - BASE_URL=http://example-ui:3000
    extends:
      file: docker-compose.base.yml
      service: monorepo-e2e
    depends_on:
      contracts:
        condition: service_completed_successfully
      example-ui:
        condition: service_healthy
      example-server:
        condition: service_healthy
