version: '3.8'

services:
  monorepo:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/monorepo

  monorepo-e2e:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.e2e
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/monorepo-e2e
